spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mysql8.0
    url: jdbc:mysql://192.168.56.110:3306/sell?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
server:
  port: 8083    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url: 
      defaultZone: http://localhost:8081/eureka/
env:
  dev
