spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mysql8.0
    url: jdbc:mysql://192.168.56.110:3306/sell?useUnicode=true&characterEncoding=UTF-8
env: dev
